### ISSUE TITLE
Unable to login, verification email not sent

### ISSUE THREAD

**Issue by ale0xb** [providedh/osf.io#1]
I'm having some trouble trying to log in the site [http://localhost:5000](http://localhost:5000). I can sign up but the verification email never shows up in my inbox. 
I can tell the email is being generated from the template by looking at the logs. 

Is there something I'm missing @michalkozak?

**Comment by michalkozak** [comment]
Hi Alex
After registering you have to verify your email address. An email with confirmation link was sent to you. But if you hadn't configured email sending, you need to read this email from logs of web container:
`docker-compose logs -f --tail 1000 web`
Try to find the following:
> web_1               | [website.mails.mails]  DEBUG: Sending email...
> web_1               | [website.mails.mails]  DEBUG: To: your@email.address

Below you will find:
> web_1               |     Please verify your email address by visiting this link:<br>
> web_1               |     <br>
> web_1               |     http://localhost:5000/confirm/erpgv/682R6Dsmp1E7aOYOZ96TcqmBaTox0t/<br>

If your registration link has expired, you have to register one more time.

I think it's the best way for development. There is no need to configure email sending via SendGrid, what is necessary for production.

**Comment by ale0xb** [comment]
Thanks Michał,
I missed the URL in the template, my account is now activated and ready to be used.
I will update the README to include this.
